"""initial schema

Revision ID: 67b6d9942cfc
Revises: 
Create Date: 2026-10-01 22:35:37.716753
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67b6d9942cfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('compact_resume', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('desired_salary_from', sa.Integer(), nullable=True),
    sa.Column('desired_salary_to', sa.Integer(), nullable=True),
    sa.Column('match_threshold', sa.SmallInteger(), server_default=sa.text('70'), nullable=False),
    sa.Column('preferred_work_formats', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('match_threshold >= 0 AND match_threshold <= 100', name='ck_user_profiles_match_threshold'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hh_vacancy_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('company_name', sa.String(length=512), nullable=True),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), server_default=sa.text("'RUR'"), nullable=True),
    sa.Column('experience', sa.String(length=64), nullable=True),
    sa.Column('employment_form', sa.String(length=64), nullable=True),
    sa.Column('work_format', sa.String(length=64), nullable=True),
    sa.Column('schedule', sa.String(length=128), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'raw'"), nullable=False),
    sa.Column('match_score', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('auto', 'group', 'manual')", name='ck_vacancies_source'),
    sa.CheckConstraint("status IN ('raw', 'analyzed', 'letter_ready', 'applied', 'error')", name='ck_vacancies_status'),
    sa.CheckConstraint('match_score >= 0 AND match_score <= 100', name='ck_vacancies_match_score'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vacancies_user_created_at', 'vacancies', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_vacancies_user_status', 'vacancies', ['user_id', 'status'], unique=False)
    op.create_index('uq_vacancies_user_hh_vacancy', 'vacancies', ['user_id', 'hh_vacancy_id'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.SmallInteger(), nullable=True),
    sa.Column('match_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('match_score >= 0 AND match_score <= 100', name='ck_analyses_match_score'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id')
    )
    op.create_table('cover_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('raw_llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('progress_current', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('progress_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('related_vacancy_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['related_vacancy_id'], ['vacancies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_status_created_at', 'tasks', ['status', 'created_at'], unique=False)
    op.create_index('ix_tasks_status_pending', 'tasks', ['status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_status', table_name='tasks')
    op.drop_index('ix_tasks_status_pending', table_name='tasks', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_tasks_status_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('cover_letters')
    op.drop_table('analyses')
    op.drop_index('uq_vacancies_user_hh_vacancy', table_name='vacancies')
    op.drop_index('ix_vacancies_user_status', table_name='vacancies')
    op.drop_index('ix_vacancies_user_created_at', table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_table('user_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
